### ISSUE TITLE
Allow "export FOO=bar" in .env to be able to source it in bash.

### ISSUE THREAD

**Issue by berkes** [numToStr/zenv#23]
Thanks for the fantastic implementation of a .env loader. It's speed, simplicity and portability make it far superior to the ruby, java- and typescript versions I had to use before. 

I'd like to suggest a feature-requests. I can work on them, if wanted. I am not sure if this is the right place to propose such a feature-request, though. Feel free to just close or delete it, if this not the right place.

In order to make my .env files a tad more portable, I used to write them with an `export` on each line. From [bkeepers/dotenv](https://github.com/bkeepers/dotenv):

> You may also add export in front of each line so you can source the file in bash:
> 
> export S3_BUCKET=YOURS3BUCKET
> export SECRET_KEY=YOURSECRETKEYGOESHERE

The benefit is that you can easily source this in bash. `source .env.test` to have the env vars in the session.

Zenv ignores these entries. It would be nice if it either fails with an error, when not reading such a line, or, better even, if it parses these too; simply ignoring the "export".

**Comment by numToStr** [comment]
> Thanks for the fantastic implementation of a .env loader. It's speed, simplicity and portability make it far superior to the ruby, java- and typescript versions I had to use before.

Thanks for the kind words. It's great this is working for you :)

> In order to make my .env files a tad more portable, I used to write them with an `export` on each line. From [bkeepers/dotenv](https://github.com/bkeepers/dotenv):
> The benefit is that you can easily source this in bash. source .env.test to have the env vars in the session.
> Zenv ignores these entries. It would be nice if it either fails with an error, when not reading such a line, or, better even, if it parses these too; simply ignoring the "export".

Ahh, I thought about making `export` statement valid before but I wasn't motivated enough to do that. But I guess there is no harm in supporting `export` statement. If you'd like to implement it then It would be great. I'll be happy to guide you :)

**Comment by numToStr** [comment]
Closed via #24
